#!/usr/bin/env python3
"""Mneme compiler scaffold.

Builds a first-pass compiled memory pack from OpenClaw-style memory sources
without committing any real private output to the repo.

This is intentionally conservative:
- reads MEMORY.md + memory/*.md
- generates compiled/*.md artifacts
- keeps provenance (source file list)
- applies basic secret redaction in generated text

The output is a starting point for human/agent review, not final truth.
"""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable


CATEGORY_RULES = {
    "projects": [
        r"\bproject\b", r"\brepo\b", r"\bbranch\b", r"\bdeploy\b", r"\blive\b",
        r"\bpath\b", r"\bworktree\b", r"\bfrontend\b", r"\bbackend\b", r"\bmap\b",
    ],
    "systems": [
        r"\bhost\b", r"\bserver\b", r"\bssh\b", r"\bgateway\b", r"\bnats\b",
        r"\bmemory\b", r"\bmysql\b", r"\bmqtt\b", r"\bforgejo\b", r"\bapi\b",
    ],
    "decisions": [
        r"\bdecid", r"\bhard rule\b", r"\bdo not\b", r"\bmust\b", r"\bshould\b",
        r"\bprefer\b", r"\brule\b", r"\bchosen\b", r"\blocked\b",
    ],
    "incidents": [
        r"\bincident\b", r"\broot cause\b", r"\boutage\b", r"\bfailed\b", r"\bbroken\b",
        r"\bcompromise\b", r"\bspike\b", r"\bcpu\b", r"\bram\b", r"\bfix\b",
    ],
}

SECRET_PATTERNS = [
    (re.compile(r"ghp_[A-Za-z0-9_]+"), "ghp_[REDACTED]"),
    (re.compile(r"(token\s*[:=]\s*)([^\s,`]+)", re.I), r"\1[REDACTED]"),
    (re.compile(r"(api[_-]?key\s*[:=]\s*)([^\s,`]+)", re.I), r"\1[REDACTED]"),
    (re.compile(r"(pass(word)?\s*[:=]\s*)([^\s,`]+)", re.I), r"\1[REDACTED]"),
    (re.compile(r"(botToken\s*[:=]\s*)([^\s,`]+)", re.I), r"\1[REDACTED]"),
]


@dataclass
class SourceLine:
    file: str
    line_no: int
    text: str


def redact(text: str) -> str:
    out = text
    for pattern, repl in SECRET_PATTERNS:
        out = pattern.sub(repl, out)
    return out


def source_files(root: Path) -> list[Path]:
    files: list[Path] = []
    memory_md = root / "MEMORY.md"
    if memory_md.exists():
        files.append(memory_md)
    memory_dir = root / "memory"
    excluded = {
        "projects.md",
        "systems.md",
        "decisions.md",
        "incidents.md",
        "timeline.md",
    }
    if memory_dir.exists():
        for path in sorted(memory_dir.glob("*.md")):
            if path.name in excluded:
                continue
            if path.name.endswith("-memory-pre-trim.md"):
                continue
            files.append(path)
    return files


def iter_candidate_lines(path: Path, root: Path) -> Iterable[SourceLine]:
    for i, raw in enumerate(path.read_text(errors="replace").splitlines(), start=1):
        line = raw.strip()
        if not line:
            continue
        if line.startswith("#") or line.startswith("-") or line.startswith("*"):
            yield SourceLine(str(path.relative_to(root)), i, redact(line))


def matches_any(text: str, patterns: list[str]) -> bool:
    lower = text.lower()
    return any(re.search(p, lower) for p in patterns)


def collect(root: Path) -> dict[str, list[SourceLine]]:
    collected = {k: [] for k in CATEGORY_RULES}
    files = source_files(root)
    for path in files:
        for item in iter_candidate_lines(path, root):
            for category, patterns in CATEGORY_RULES.items():
                if matches_any(item.text, patterns):
                    collected[category].append(item)
    return collected


def unique_lines(items: list[SourceLine], limit: int = 80) -> list[SourceLine]:
    seen: set[str] = set()
    out: list[SourceLine] = []
    for item in items:
        key = item.text.lower()
        if key in seen:
            continue
        seen.add(key)
        out.append(item)
        if len(out) >= limit:
            break
    return out


def write_category(path: Path, title: str, items: list[SourceLine], sources: list[str]) -> None:
    lines = [
        f"# Compiled Memory — {title}",
        "",
        "> Generated by `scripts/mneme_compile_memory.py`. Review before treating as truth.",
        "",
        "## Candidate facts",
    ]
    if items:
        for item in items:
            lines.append(f"- {item.text}  ")
            lines.append(f"  Source: `{item.file}:{item.line_no}`")
    else:
        lines.append("- No candidate facts found in this pass.")
    lines.extend([
        "",
        "## Sources",
        *[f"- `{s}`" for s in sources],
        "",
    ])
    path.write_text("\n".join(lines))


def build_timeline(root: Path, out_path: Path, sources: list[str]) -> None:
    entries: list[tuple[str, str, str]] = []
    date_re = re.compile(r"(20\d{2}-\d{2}-\d{2})")
    for rel in sources:
        path = root / rel
        text = path.read_text(errors="replace").splitlines()
        file_date = None
        m = date_re.search(rel)
        if m:
            file_date = m.group(1)
        for line in text:
            stripped = line.strip()
            if stripped.startswith("## "):
                title = redact(stripped[3:])
                entries.append((file_date or "undated", title, rel))
    entries.sort()
    lines = [
        "# Compiled Memory — Timeline",
        "",
        "> Generated by `scripts/mneme_compile_memory.py`. Review before treating as truth.",
        "",
    ]
    if entries:
        current = None
        for date, title, rel in entries[:200]:
            if date != current:
                lines.append(f"## {date}")
                current = date
            lines.append(f"- {title}  ")
            lines.append(f"  Source: `{rel}`")
    else:
        lines.append("- No timeline entries found.")
    lines.extend(["", "## Sources", *[f"- `{s}`" for s in sources], ""])
    out_path.write_text("\n".join(lines))


def build_report(out_dir: Path, sources: list[str], collected: dict[str, list[SourceLine]]) -> None:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# Mneme Compile Report",
        "",
        f"Generated: {now}",
        "",
        "## Inputs",
        *[f"- `{s}`" for s in sources],
        "",
        "## Candidate counts",
    ]
    for category, items in collected.items():
        lines.append(f"- {category}: {len(unique_lines(items))}")
    lines.extend([
        "",
        "## Notes",
        "- This pass is deterministic and conservative.",
        "- It preserves source references instead of pretending to know final truth.",
        "- Review, trim, and promote before merging into long-term memory.",
        "",
    ])
    (out_dir / "report.md").write_text("\n".join(lines))


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a first-pass compiled memory pack.")
    parser.add_argument("--root", default=".", help="Workspace root containing MEMORY.md and memory/*.md")
    parser.add_argument("--out", default="compiled", help="Output directory for compiled files")
    args = parser.parse_args()

    root = Path(args.root).expanduser().resolve()
    out_dir = Path(args.out).expanduser().resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    files = source_files(root)
    sources = [str(p.relative_to(root)) for p in files]
    collected = collect(root)

    write_category(out_dir / "projects.md", "Projects", unique_lines(collected["projects"]), sources)
    write_category(out_dir / "systems.md", "Systems", unique_lines(collected["systems"]), sources)
    write_category(out_dir / "decisions.md", "Decisions", unique_lines(collected["decisions"]), sources)
    write_category(out_dir / "incidents.md", "Incidents", unique_lines(collected["incidents"]), sources)
    build_timeline(root, out_dir / "timeline.md", sources)
    build_report(out_dir, sources, collected)

    print(f"Compiled memory pack written to {out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
